name = 'Oakley'
license = 'MIT'
licenselink = 'https://github.com/scalka/sylwia_creates/blob/main/themes/oakley/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/scalka/sylwia_creates/tree/main/themes/oakley'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'portfolio', 'digital garden']
features = ['minimal', 'playful', 'accessible']

# If the theme has a single author
[author]
  name = 'Sylwia Całka-Verhulst'
  homepage = 'Your website'
